name: Run KaleidoFinance Bot

on:  
  workflow_dispatch:  # Bisa dijalankan manual
  schedule:
    - cron: "0 */6 * * *"  # Otomatis jalan setiap 6 jam

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Run Bot
        run: npm run start
0x5Eebcfd2e103705Bd2F279008c846387b156cb11
